### ISSUE TITLE
Hope that the plot functions in this package can support the randomforest object from randomForest pkg.

### ISSUE THREAD

**Issue by lincj1994** [jasenfinch/metabolyseR#88]
Hi. I found this cool pkg by accident and the plot functions generate really nice plots.
Hope that the plot functions in this package can support the randomforest object from randomForest pkg since most users create a RF model using randomForest pkg.
Thanks.

**Comment by jasenfinch** [comment]
The *metabolyseR* package uses the *randomForest* package to provide a convenient interface for users using the S4 object system. The `returnModels` argument of the [`randomForest`](https://jasenfinch.github.io/metabolyseR/reference/randomForest.html) generic allows users to return the S3 `randomForest` class model objects of the *randomForest* package.
