### ISSUE TITLE
 SUMMARY: processing the following file failed:      ‘missForest_1.4.Rnw’

### ISSUE THREAD

**Issue by Akash20999** [jasenfinch/metabolyseR#89]
Dear Jasen, 

Very nice package to begin with! Unfortunately, I haven't been able to use it since some files are not being processed (see title for the error). Could you have a look at it? Thank you.

**Comment by jasenfinch** [comment]
This looks like it is an issue concerning the documentation of the *missForest* package, a dependency of *metabolyseR*.
