### ISSUE TITLE
Vignettes issue

### ISSUE THREAD

**Issue by Stakumar** [jasenfinch/metabolyseR#90]
The vignettes are not getting installed during metabolyseR installation.
The error message as given below!

v  checking for file 'C:\Users\abservice\AppData\Local\Temp\RtmpeyzgWe\remotesd69083f312a0e\jasenfinch-metabolyseR-5b3a032/DESCRIPTION' ... 
-  preparing 'metabolyseR':
v  checking DESCRIPTION meta-information ... 
-  installing the package to build vignettes
E  creating vignettes (15.7s)
   --- re-building 'metabolyseR.Rmd' using rmarkdown
   Error: processing vignette 'metabolyseR.Rmd' failed with diagnostics:
   there is no package called 'prettydoc'
   --- failed re-building 'metabolyseR.Rmd'
   
   --- re-building 'modelling.Rmd' using rmarkdown
   Error: processing vignette 'modelling.Rmd' failed with diagnostics:
   there is no package called 'prettydoc'
   --- failed re-building 'modelling.Rmd'
   
   --- re-building 'pre_treatment.Rmd' using rmarkdown
   Error: processing vignette 'pre_treatment.Rmd' failed with diagnostics:
   there is no package called 'prettydoc'
   --- failed re-building 'pre_treatment.Rmd'
   
   --- re-building 'quick_start.Rmd' using rmarkdown
   Error: processing vignette 'quick_start.Rmd' failed with diagnostics:
   there is no package called 'prettydoc'
   --- failed re-building 'quick_start.Rmd'
   
   SUMMARY: processing the following files failed:
     'metabolyseR.Rmd' 'modelling.Rmd' 'pre_treatment.Rmd'
     'quick_start.Rmd'
   
   Error: Vignette re-building failed.
   Execution halted
Error: Failed to install 'metabolyseR' from GitHub:
  ! System command 'Rcmd.exe' failed
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

**Comment by Stakumar** [comment]
Can you please help me sorting this? I wish to try this package for metabolomics data analysis.

**Comment by anasmhana** [comment]
devel

**Comment by anasmhana** [comment]
> لم يتم تثبيت المقالات القصيرة أثناء تثبيت التمثيل الغذائي. رسالة الخطأ على النحو المبين أدناه!
> 
> v التحقق من الملف 'C: \ Users \ abservice \ AppData \ Local \ Temp \ RtmpeyzgWe \ remotesd69083f312a0e \ jasenfinch-metabolyseR-5b3a032 / DESCRIPTION' ...
> 
> * تحضير `` metabolyseR '': 
>   v فحص المعلومات الوصفية الوصفية ...
> * تثبيت الحزمة لإنشاء المقالات القصيرة 
>   E إنشاء المقالات النصفية (15.7 ثانية) 
>   --- إعادة بناء `` metabolyseR.Rmd '' باستخدام 
>   خطأ rmarkdown: فشلت معالجة المقالة القصيرة `` metabolyseR.Rmd '' مع التشخيص: 
>   لا توجد حزمة تسمى 'prettydoc' 
>   --- فشل إعادة بناء "التمثيل الغذائي R.Rmd"
>   --- إعادة بناء 'modelling.Rmd' باستخدام 
>   خطأ rmarkdown: فشلت معالجة المقالة القصيرة 'modelling.Rmd' مع التشخيص: 
>   لا توجد حزمة تسمى 'prettydoc' 
>   --- فشلت إعادة بناء 'modelling.Rmd'
>   --- إعادة بناء 'pre_treatment.Rmd' باستخدام 
>   خطأ rmarkdown: فشلت معالجة المقالة القصيرة 'pre_treatment.Rmd' مع التشخيص: 
>   لا توجد حزمة تسمى 'prettydoc' 
>   --- فشلت عملية إعادة البناء 'pre_treatment.Rmd'
>   --- إعادة بناء 'quick_start.Rmd' باستخدام 
>   خطأ rmarkdown: فشلت معالجة المقالة القصيرة 'quick_start.Rmd' مع التشخيص: 
>   لا توجد حزمة تسمى 'prettydoc' 
>   --- فشلت عملية إعادة البناء 'quick_start.Rmd'
>   الملخص: فشلت معالجة الملفات التالية: 
>   'metabolyseR.Rmd' 'modelling.Rmd' 'pre_treatment.Rmd' 
>   'quick_start.Rmd'
>   خطأ: فشلت إعادة إنشاء نقوش الصورة النصفية. 
>   توقف التنفيذ 
>   خطأ: فشل في تثبيت 'metabolyseR' من GitHub 
>   :! فشل أمر النظام 'Rcmd.exe' 
>   بالإضافة إلى ذلك: رسائل التحذير: 
>   1: في untar2 (tarfile ، files ، list ، exdir): 
>   تخطي pax global exters headers 
>   2: in untar2 (tarfile، files، list، exdir): 
>   تخطي pax global رؤوس ممتدة

**Comment by jasenfinch** [comment]
Hi, sorry for the slow reply. You can simply install the package using:
```
remotes::install_github('jasenfinch/metabolyseR')
```

Omitting the `build_vignettes` argument. The package documentation is alternatively available online [here](https://jasenfinch.github.io/metabolyseR/). If you would like to compile the vignettes locally, you can use the following:
```
remotes::install_github('jasenfinch/metabolyseR',build_vignettes = TRUE,dependencies = TRUE)
```

The installation instructions have been corrected in the commits 
[cc79828](https://github.com/jasenfinch/metabolyseR/commit/cc79828154d9633bd87fc42353baa167c948acbc) and [029a439](https://github.com/jasenfinch/metabolyseR/commit/029a4391b32524c1cdcda253ea3e0b3084df248e) on the `devel` branch and will be the default instructions with the upcoming release of version 0.15.0.

**Comment by Stakumar** [comment]
> Hi, sorry for the slow reply. You can simply install the package using:
> 
> ```
> remotes::install_github('jasenfinch/metabolyseR')
> ```
> 
> Omitting the `build_vignettes` argument. The package documentation is alternatively available online [here](https://jasenfinch.github.io/metabolyseR/). If you would like to compile the vignettes locally, you can use the following:
> 
> ```
> remotes::install_github('jasenfinch/metabolyseR',build_vignettes = TRUE,dependencies = TRUE)
> ```
> 
> The installation instructions have been corrected in the commits [cc79828](https://github.com/jasenfinch/metabolyseR/commit/cc79828154d9633bd87fc42353baa167c948acbc) and [029a439](https://github.com/jasenfinch/metabolyseR/commit/029a4391b32524c1cdcda253ea3e0b3084df248e) on the `devel` branch and will be the default instructions with the upcoming release of version 0.15.0.

Thank you so much. I shall try it.
